trigger:
  branches:
    include:
    - main
    - feature/*
    - fix/*
    - bug/*
    - test/*

  paths:
    include:
    - code
    exclude:
    - .attachments
    - infrastructure
    - yaml

variables:
- name: files.path
  value: code
- name: app_name
  value: 'oncall-alarm'

stages:

- stage: Dev
  displayName: 'Deploy Dev'
  condition: and(always(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: []
  variables:
  - group: 'aws-keys'
  - name: 'environment'
    value: 'dev'
  - name: 'bucket'
    value: 'my-s3-bucket'
  jobs:

  - deployment: deployDev
    displayName: Deploy Dev
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'dev-$(app_name)-app'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: templates/code-cd.yml
            parameters:
              hclServiceConnection: "hcl-svc"
              cspServiceConnection: "csp-svc"

- stage: Prod
  displayName: 'Deploy Prod'
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: []
  variables:
  - group: 'aws-keys'
  - name: 'environment'
    value: 'prod'
  - name: 'bucket'
    value: 'my-s3-bucket'
  jobs:

  - job: prodApproval
    displayName: Wait for Manual Approval
    pool: server
    timeoutInMinutes: 43800
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 43800 # task times out in 1 month
        inputs:
           notifyUsers: |
             kmartinez@welldynerx.com
           instructions: 'Please validate the build configuration and resume'
           onTimeout: 'resume'

  - deployment: deployProd
    displayName: Deploy Prod
    dependsOn: prodApproval
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'prod-$(app_name)-app'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: templates/code-cd.yaml
            parameters:
              hclServiceConnection: "hcl-svc"
              cspServiceConnection: "csp-svc"